name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

jobs:
  lint-check:
    name: golangci-lint-v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          args: --timeout 5m --config .golangci.yml
          version: v2.1.6
